# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f943a5930bfcf1962f907c155cf4ca631166c4e5f81b649c5125f6cbd2c5445d322972e54bd2118030e42924278fe32204e17af8e5180586f2a079b7a4514820

test:
  secret_key_base: 49827d50aaeded312f9dcc23fc3e433b1b557369f209b58c71056c124db7935fcaac81f004b08e2f33e45457a9a9465064970d090d0a54fab1288ca66987e06f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
